from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import openai
import os

# Initialize FastAPI app
app = FastAPI()

# Allow frontend origin
app.add_middleware(
    CORSMiddleware,
    allow_origins=["https://sitecraft-frontend.onrender.com"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Set your OpenAI API key
openai.api_key = os.getenv("OPENAI_API_KEY")

# Request model
class PromptRequest(BaseModel):
    prompt: str

@app.post("/generate-pure")
async def generate_pure_site(request: PromptRequest):
    prompt = request.prompt

    # Generate AI Image
    image_response = openai.images.generate(
        model="dall-e-3",
        prompt=prompt,
        n=1,
        size="1024x1024",
        quality="standard",
        response_format="url"
    )
    image_url = image_response.data[0].url

    # Generate Website Text Content (title, tagline, and 5 sections)
    response = openai.ChatCompletion.create(
        model="gpt-4",
        messages=[
            {
                "role": "system",
                "content": "You are a helpful assistant that writes clean HTML websites using semantic layout and modern design. Structure the website with a hero section, AI-generated image, tagline, and 5 content sections based on the user prompt. Use clear section titles and real-sounding text. Style lightly with inline CSS."
            },
            {
                "role": "user",
                "content": f"Create a clean, professional one-page HTML site based on: '{prompt}'"
            }
        ]
    )

    site_text = response.choices[0].message.content

    # Combine everything into final HTML
    html_code = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SiteCraft – AI Website</title>
  <style>
    body {{
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      background: #f8f9fa;
      color: #333;
    }}
    header {{
      background-image: url('{image_url}');
      background-size: cover;
      background-position: center;
      text-align: center;
      color: white;
      padding: 100px 20px 60px;
    }}
    header h1 {{
      font-size: 2.8rem;
      margin: 0;
    }}
    header p {{
      font-size: 1.2rem;
      margin-top: 10px;
    }}
    section {{
      padding: 40px 20px;
      max-width: 900px;
      margin: auto;
      background: white;
      margin-bottom: 20px;
      box-shadow: 0 0 10px rgba(0,0,0,0.05);
      border-radius: 8px;
    }}
    h2 {{
      font-size: 1.8rem;
      margin-bottom: 10px;
      color: #2c3e50;
    }}
    footer {{
      text-align: center;
      padding: 30px 20px;
      background: #222;
      color: #ccc;
      font-size: 0.9rem;
    }}
  </style>
</head>
<body>
  <header>
    <h1>Generated by SiteCraft</h1>
    <p>Your AI-powered website builder</p>
  </header>
  {site_text}
  <footer>
    &copy; {2025} SiteCraft. All rights reserved.
  </footer>
</body>
</html>
"""

    return {"html": html_code}
